apiVersion: v1
appVersion: v0.58.0
description: 'Feast Feature Server: Online feature serving service for Feast'
home: https://github.com/feast-dev/feast
keywords:
- machine learning
- big data
- mlops
name: feature-server
version: 0.58.0
